export default [
  {
    id: 1,
    img: '../images/image1.png',
    price: 136,
    status: 'SOLD OUT',
    rating: 5,
    quantity: 5,
    country: 'USA',
    bodyTitle: 'Life lessons with Katie Zdferes',
    openSpot: 8,
    location: 'online' ,
  },
  {
    id: 2,
    img: '../images/image1.png',
    price: 136,
    status: 'SOLD OUT',
    rating: 5,
    quantity: 5,
    country: 'USA',
    bodyTitle: 'Life lessons with Katie Zdferes',
    openSpot: 4,
    location: 'online',
  },
  {
    id: 3,
    img: '../images/image1.png',
    price: 136,
    status: 'SOLD OUT',
    rating: 5,
    quantity: 5,
    country: 'USA',
    bodyTitle: 'Life lessons with Katie Zdferes',
    openSpot: 0,
    location: 'online',
  },
  {
    id: 4,
    img: '../images/image1.png',
    price: 136,
    status: 'SOLD OUT',
    rating: 5,
    quantity: 5,
    country: 'USA',
    bodyTitle: 'Life lessons with Katie Zdferes',
    openSpot: 0,
    location: 'online',
  },
  {
    id: 5,
    img: '../images/image1.png',
    price: 136,
    status: 'SOLD OUT',
    rating: 5,
    quantity: 5,
    country: 'USA',
    bodyTitle: 'Life lessons with Katie Zdferes',
    openSpot: 0,
    location: 'online',
  },
  {
    id: 6,
    img: '../images/image1.png',
    price: 136,
    status: 'SOLD OUT',
    rating: 5,
    quantity: 5,
    country: 'USA',
    bodyTitle: 'Life lessons with Katie Zdferes',
    openSpot: 0,
    location: 'hebron',
  },
  {
    id: 7,
    img: '../images/image1.png',
    price: 136,
    status: 'SOLD OUT',
    rating: 5,
    quantity: 5,
    country: 'USA',
    bodyTitle: 'Life lessons with Katie Zdferes',
    openSpot: 0,
    location: 'hebron',
  },
  {
    id: 8,
    img: '../images/image1.png',
    price: 136,
    status: 'SOLD OUT',
    rating: 5,
    quantity: 5,
    country: 'USA',
    bodyTitle: 'Life lessons with Katie Zdferes',
    openSpot: 10,
    location: 'hebron',
  },
] 